### ISSUE TITLE
TensorFlow Error

### ISSUE THREAD

**Issue by tanueihorng** [dataplayer12/homesecurity#10]
Hi, thanks for the great work! 
Any idea why this error occurred? (i had installed tensorflow)
![hserror](https://user-images.githubusercontent.com/61866167/88613762-c4aa1300-d0c0-11ea-8b12-1eada4204faf.png)

**Comment by dataplayer12** [comment]
Hi, which version of tensorflow are you using? Also, it seems like tensorflow was not installed correctly since it is unable to find your CUDA runtime library (see the error about `libcudart.so`)

**Comment by dataplayer12** [comment]
Hi, were you able to resolve this error?

**Comment by tanueihorng** [comment]
Hi @dataplayer12 
Sorry for the late reply

Since my TensorFlow was not installed correctly in the first place, is there a way to uninstall my current TensorFlow then reinstall again?

**Comment by dataplayer12** [comment]
You should be able to uninstall it with `pip uninstall tensorflow`. If that doesn't work, create a virtual environment and install tensorflow again only in that environment. Please make sure that your CUDA installation is in the default directory. If you are installing tensorflow from the pre-compiled wheels by NVIDIA, it will assume that your CUDA installation is in the default directory for that version of JetPack. Good luck.

**Comment by tanueihorng** [comment]
Hi @dataplayer12 
So I just need to download TensorFlow from the link below right? and how to make sure the CUDA is in the default directory when I flashed the image in SD card?
https://forums.developer.nvidia.com/t/official-tensorflow-for-jetson-nano/71770 

`sudo apt-get install libhdf5-serial-dev hdf5-tools libhdf5-dev zlib1g-dev zip libjpeg8-dev liblapack-dev libblas-dev gfortran
sudo apt-get install python3-pip
sudo pip3 install -U pip
sudo pip3 install -U pip testresources setuptools numpy==1.16.1 future==0.17.1 mock==3.0.5 h5py==2.9.0 keras_preprocessing==1.0.5 keras_applications==1.0.8 gast==0.2.2 futures protobuf pybind11`

**Comment by dataplayer12** [comment]
Make sure you are using the instruction for the correct version of JetPack, and the installation should proceed smoothly. Usually CUDA will be in the default directory, unless you have installed a newer version of CUDA on an older JetPack. Also, please install only `tf 1.x`. I have not tested this project with `2.x` and it is quite likely that functionality will break on the newer version.

**Comment by tanueihorng** [comment]
Thanks for the guide!!!

I'll install it by following the steps below for tf1.15
1) sudo apt-get install libhdf5-serial-dev hdf5-tools libhdf5-dev zlib1g-dev zip libjpeg8-dev liblapack-dev libblas-dev gfortran
2) sudo apt-get install python3-pip
3) sudo pip3 install -U pip
4) sudo pip3 install -U pip testresources setuptools numpy==1.16.1 future==0.17.1 mock==3.0.5 h5py==2.9.0 keras_preprocessing==1.0.5 keras_applications==1.0.8 gast==0.2.2 futures protobuf pybind11
5) $ sudo pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v44 ‘tensorflow<2’

No problem right?

**Comment by dataplayer12** [comment]
Yes, this should work perfectly.

**Comment by tanueihorng** [comment]
Hi i got this error while attempting the Forth Command

https://forums.developer.nvidia.com/t/official-tensorflow-for-jetson-nano/71770/154?u=tan_uh

**Comment by dataplayer12** [comment]
Can you do a `pip install cython` before running the fourth command again? Cython usually gives a lot of problems so you may have to search for an older version and install that before continuing.

**Comment by tanueihorng** [comment]
Forth command issue solved !

![bash](https://user-images.githubusercontent.com/61866167/89363278-5c7fb080-d702-11ea-9d24-bcf48f3dd89e.png)
But when i type the last command, it appear this error

**Comment by dataplayer12** [comment]
Hi, sorry for being late in getting back to you. The simplest way is to go to the link you are specifying and download the wheel file on your own or by using `wget`. Then, you can just use pip install file.whl

**Comment by tanueihorng** [comment]
Hi @dataplayer12 
Thank you for being patient with me! I'm a student and had to learn everything from scratch. 

![Screenshot from 2020-08-07 09-53-10](https://user-images.githubusercontent.com/61866167/89600138-dd21e680-d893-11ea-9e83-77a05ef54e1c.png)

Which Tf1 version you using in the project? cuz i want to install the compatible version to avoid any issue 

fter downloading the wheel file just type this command on terminal right 
( $ sudo pip install tensorflow-1.15.2+nv20.4-cp36-cp36m-linux_aarch64.whl ) 

Thanks a lot!

**Comment by dataplayer12** [comment]
It seems like you have the latest version of CUDA, so I suggest going with the latest version of tf1, `1.15.3`. The specific version of tf1 does not matter. However, there is a huge difference between tf1 and tf2, so that does matter. Feel free to ask more questions. I have also learnt by asking around, so I am always ready to pass on knowledge in the spirit of open source.

**Comment by tanueihorng** [comment]
Tensorflow installed successfully! But i got some problem when running launch.sh 

![basherror](https://user-images.githubusercontent.com/61866167/89611915-ff762d00-d8b0-11ea-933b-e9d295073842.png)

I had also added the email and password on confidental.txt 
{"recepients": ["xxx@hotmail.com", "email2"], "myemail": "xxx@hotmail.com", "mypass": "xxxxxxxxx"}

**Comment by dataplayer12** [comment]
Hi, before launching the program for the first time, you need to compile the tensorflow inference graph for your version of tf and JetPack. Please see the instructions for Jetson Nano again. You just need to run a script which will do this for you. Let me know if you have any more questions.

**Comment by dataplayer12** [comment]
Please wait. I checked again and this may not solve your issue. Can you tell which version of python are you using?

**Comment by tanueihorng** [comment]
When I tried to compile the tennsorflow, new error occurred 
![compileerror2](https://user-images.githubusercontent.com/61866167/89614374-dd7fa900-d8b6-11ea-8a60-aca124d68f22.png)

**Comment by tanueihorng** [comment]
> Please wait. I checked again and this may not solve your issue. Can you tell which version of python are you using?

Python 3.6.9 (Default )

**Comment by dataplayer12** [comment]
For some reason, it is unable to find the graph file, which is definitely present in the GitHub repo. Can you check that this file is present in the local version of the repo you cloned? Which version of JetPack are you using? I will try to reproduce this error this evening and update the repo if necessary.

**Comment by tanueihorng** [comment]
This is what i found under Human Detection file
![graph](https://user-images.githubusercontent.com/61866167/89617157-461d5480-d8bc-11ea-802f-adbcb397fffd.png)

Jetpack 4.4 (Just installed this month)
CUDA 10.2.89
TensorFlow 1.15.3
Python 3.6.9

**Comment by quarterturn** [comment]
I got the same error and was able to force it to work by setting an absolute path to the file.

`
62 model_path = '/home/[user]/project/homesecurity/human_detection/ssd_mobilenet_v1_coco_2017_11_17/frozen_inference_graph.pb'
`
It looks like you're doing the right thing in jetsonano/securitycamnano.py with regards to appending the path to human_detection directory but it's going wrong somewhere.

I'm on:
user@jetson-nano1:~/project/homesecurity/jetsonano$ cat /etc/nv_tegra_release 
# R32 (release), REVISION: 4.3, GCID: 21589087, BOARD: t210ref, EABI: aarch64, DATE: Fri Jun 26 04:38:25 UTC 2020
user@jetson-nano1:~/project/homesecurity/jetsonano$ uname -a
Linux jetson-nano1 4.9.140-tegra #3 SMP PREEMPT Thu Jul 16 13:41:48 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

tensorflow==1.15.2

**Comment by dataplayer12** [comment]
Thanks for the workaround. The path works correctly on most systems but seems to break for some people and I do not know why. @tanueihorng might this solve your problem?

**Comment by tanueihorng** [comment]
Hi @quarterturn @dataplayer12 
Can I know how to set the absolute path to the file ?

Thanks!!!

**Comment by quarterturn** [comment]
line 62 in file human_detect.py
provide the full path to where yo u have frozen_inference_graph.pb installed

**Comment by tanueihorng** [comment]
Thanks! @quarterturn @dataplayer12 
It managed to record a video when motion is detected. However, I didn't receive any recording email in my inbox. 
[bashlaunch.txt](https://github.com/dataplayer12/homesecurity/files/5073264/bashlaunch.txt)

Any idea how to solve this? 

I had also added the email and password on confidental.txt 
{"recepients": ["xxx@hotmail.com", "email2"], "myemail": "xxx@hotmail.com", "mypass": "xxxxxxxxx"}

This is where I created the text file (/home/singtel/homesecurity)
![homesecu](https://user-images.githubusercontent.com/61866167/90226937-5eeeb280-de46-11ea-8503-1abc5a0753f3.png)

**Comment by dataplayer12** [comment]
I have never tried hotmail, but on gmail you have to enable unsecure apps to allow your pi/jetson to login and send emails. Please check your inbox or notifications and you might have received some info like 'a sign in attempt was blocked'. Once the detection and recording is working, this is the only possible snag and obviously your device needs to be connected to the internet as well.

**Comment by tanueihorng** [comment]
Hi @dataplayer12 thanks for the fast reply

After turn on the less secure apps in gmail, I still unable to received the email.
One extra question here, what should I do to use IP Camera instead of existing pi camera (i got the rtsp url but dunno where to insert)

Thanks a lot

**Comment by tanueihorng** [comment]
Sorry to disturb you again

![error](https://user-images.githubusercontent.com/61866167/90229536-a70fd400-de4a-11ea-84a5-d803a622e416.png)
 
Why do I have this error when running the third time ?

**Comment by dataplayer12** [comment]
Hi, the error states that the camera could not be initialized. This means that the last time you quit the program, the camera was not shut down correctly. The error is originating from NVIDIA's camera api, so I can't say exactly what went wrong. In any case, rebooting your nano will fix this problem.
About the email problem, you state that you are using hotmail in your confidential.txt, so I wonder why are you changing the settings for gmail. Also, the change in settings is required only for the account that is sending the email. The recipient accounts do not need to make any changes.

**Comment by tanueihorng** [comment]
I already changed it to gmail (yes, the sending email) 

and How to shut down the camera correctly when i wan to quite the program ? (Ctrl + C)?

**Comment by dataplayer12** [comment]
Ctrl+C should work for shutting down the camera, but sometimes the `libargus` subprocess(es) does not close successfully. So, if you face this problem again, please use `ps aux|grep argus` to list the processes running for `libargus` and kill them by their pid. See this for [more](https://www.linux.com/training-tutorials/how-kill-process-command-line/). Something like `pkill libargus` might also work, although I haven't tried it myself.

Any luck with the email? Please make sure that you have followed the steps from [here](https://support.google.com/accounts/answer/6010255?hl=en). If it still doesn't work, you can try using an app specific password.

**Comment by dataplayer12** [comment]
@tanueihorng any progress on this issue? If the issue is resolved, please close it.

**Comment by dataplayer12** [comment]
Closing because issue seems to have been resolved.
