### ISSUE TITLE
Which JetPack Version for Xavier

### ISSUE THREAD

**Issue by DennisFaucher** [dataplayer12/homesecurity#16]
Hi. I am running JetPack version 4.2.1 on my Xavier. When I run launch.sh, xavier_surveillance.py fails on multiple libraries as they are too new plus the CUDA is not 10.0. What JetPack load did you successfully test with? TIA.

Failed library versions:
* libopencv_highgui
* libopencv_videoio
* libopencv_imgcodecs
* libopencv_imgproc
* libopencv_imgcodecs
* libopencv_imgproc
* libopencv_core
* libcudart
* libcublas
* libcurand
* libcudnn

Renamed the libraries for fun and received a core dump.

**Comment by dataplayer12** [comment]
Hi, this problem is likely not related to Jetpack or CUDA version at all. For some reason, in my experience, the CUDA include path is not exported as an environment variable on the Xavier by default. Since you are getting errors for some very fundamental libraries, please export the CUDA path as an environment variable. I suggest the following:

```Shell
export PATH=/usr/local/cuda-10.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
Please replace `10.0` with the appropriate version on your xavier. Hopefully this resolves the issue. If it works, append this to your `.bashrc` or `.bash_profile` file.

**Comment by DennisFaucher** [comment]
My LD_LIBRARY_PATH and PATH already included CUDA 10.2. Any other ideas?

LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64:

PATH=/home/dennis/.local/bin:/usr/local/cuda-10.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by DennisFaucher** [comment]
My OpenCV libraries all seem to be in /usr/lib/aarch64-linux-gnu so I tried this:

export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu:$LD_LIBRARY_PATH
$ bash launch.sh
Traceback (most recent call last):
  File "xavier/xavier_surveillance.py", line 11, in <module>
    import darknet
  File "/home/dennis/external/homesecurity/xavier/darknet.py", line 123, in <module>
    lib = CDLL("/home/dennis/external/homesecurity/human_detection/xavier/libdarknet.so", RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopencv_highgui.so.3.3: cannot open shared object file: No such file or directory

**Comment by dataplayer12** [comment]
Hi, there are a few changes in JetPack which have broken support on the xavier, such as the use of opencv4 and a change in the path where opencv libraries are stored. Did you have any problems in compiling darknet? Also, since you have found the location of opencv binaries, please make sure you have read/write/execute permissions on this folder. If yes and the script still doesn't work, please add this location to your `PYTHONPATH` variable, something like:
```Shell
export PYTHONPATH=/usr/lib/aarch64-linux-gnu/:$PYTHONPATH
```

**Comment by DennisFaucher** [comment]
Finally had a chance to test this. Good idea. My libraries have a different version name that that requested.

$ export PYTHONPATH=/usr/lib/aarch64-linux-gnu/:$PYTHONPATH

$ bash launch.sh
Traceback (most recent call last):
  File "xavier/xavier_surveillance.py", line 11, in <module>
    import darknet
  File "/home/dennis/external/homesecurity/xavier/darknet.py", line 123, in <module>
    lib = CDLL("/home/dennis/external/homesecurity/human_detection/xavier/libdarknet.so", RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopencv_highgui.so.3.3: cannot open shared object file: No such file or directory
dennis@xavier:~/external/homesecurity$ find /usr -name libopencv_highgui*
/usr/lib/aarch64-linux-gnu/libopencv_highgui.so.3.2
/usr/lib/aarch64-linux-gnu/libopencv_highgui.so.3.2.0
/usr/lib/aarch64-linux-gnu/libopencv_highgui.so.4.1.1
/usr/lib/aarch64-linux-gnu/libopencv_highgui.so
/usr/lib/aarch64-linux-gnu/libopencv_highgui.so.4.1
/usr/lib/aarch64-linux-gnu/libopencv_highgui.a

**Comment by DennisFaucher** [comment]
Oh, that's an interesting direction. Let me look into the darknet install. TY.

**Comment by DennisFaucher** [comment]
Did not realize I needed to run xavier/compile_darknet.sh. Trying that now.

**Comment by DennisFaucher** [comment]
Closing. Too much trouble right now.

**Comment by dataplayer12** [comment]
Yes, this is the error I expected you would get. This is a problem with JetPack 4.4. I will fix this whenever I can and also add another way to run inference using `jetson-inference` library. Please wait.
